# Generated by Django 4.2.11 on 2024-05-05 19:33

import Store.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
                ('vendor_code', models.CharField(max_length=150, unique=True)),
                ('on_time_delivery_rate', models.FloatField(validators=[Store.models.validate_positive_percentage])),
                ('quality_rating_avg', models.FloatField(validators=[Store.models.validate_quality_rating_avg])),
                ('average_response_time', models.FloatField(validators=[Store.models.validate_positive_time_in_minutes])),
                ('fulfillment_rate', models.FloatField(validators=[Store.models.validate_positive_percentage])),
            ],
            options={
                'db_table': 'Vendor_details',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=100)),
                ('quality_rating', models.FloatField(null=True, validators=[Store.models.validate_quality_rating_avg])),
                ('issue_date', models.DateTimeField()),
                ('acknowledgement_date', models.DateTimeField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.vendor')),
            ],
            options={
                'db_table': 'Purchase_details',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField(validators=[Store.models.validate_positive_percentage])),
                ('quality_rating_avg', models.FloatField(validators=[Store.models.validate_quality_rating_avg])),
                ('average_response_time', models.FloatField(validators=[Store.models.validate_positive_time_in_minutes])),
                ('fulfillment_rate', models.FloatField(validators=[Store.models.validate_positive_percentage])),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.vendor')),
            ],
            options={
                'db_table': 'Performance_details',
            },
        ),
    ]
