# Generated by Django 4.2.11 on 2024-05-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_performance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='on_time_delievery_rate',
            new_name='on_time_delivery_rate',
        ),
    ]
