# Generated by Django 4.2.11 on 2024-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_rename_on_time_delievery_rate_performance_on_time_delivery_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quality_rating_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
